languageCode = "en-us"
title = "Sean's Tech Blog"
baseurl = "http://hubbins.github.io/"
theme = "beautifulhugo"

[Params]
  disqusShortname = "hubbins"
  subtitle = "Java, .NET, other Tech"

[Author]
  name = "Sean O'Connor"
  email = "blog@hubbins.com"
  github = "hubbins"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3


