languageCode = "en-us"
title = "Sean's Tech Blog"
baseurl = "http://hubbins.github.io/"
theme = "beautifulhugo"

[Params]
  disqusShortname = "hubbins"
  subtitle = "Java, .NET, other Tech"

[Author]
  name = "Sean O'Connor"
  email = "blog@soconnor.org"
  github = "hubbins"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3

